In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import seaborn as sns

In [43]:
exp_dir = 'exps/1_hr_25x_real_rand/'
const_score_list, opt_score_list = [], []

for i in range(25):
    
    const_df = pd.read_csv(exp_dir + 'const_run_' + str(i)+ '.csv', index_col = 0)
    opt_df = pd.read_csv(exp_dir + 'opt_run_' + str(i)+ '.csv', index_col = 0)
    const_score_list.append(np.max(const_df['total_score_hist']))
    opt_score_list.append(np.max(opt_df['total_score_hist']))
    
    fig, ax = plt.subplots(2)
    
    ax[0].plot(const_df['total_score_hist'], label='Value Generated, Constant Belt Speed: ' + str(np.round(np.max(const_df['total_score_hist']), decimals= 2)))
    ax[0].plot(opt_df['total_score_hist'], label='Value Generated, Optimized Belt Speed: ' + str(np.round(np.max(opt_df['total_score_hist']), decimals= 2)))
    ax[0].legend()
    
    
    ax[1].plot(const_df['speed_hist'], label='Belt Speed: Constant')
    ax[1].plot(opt_df['speed_hist'], label='Belt Speed: Optimized')
    ax[1].legend()
    plt.show()

const_score = np.array(const_score_list)
opt_score = np.array(opt_score_list)

/tmp/ipykernel_663875/3684202249.py:11: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.



In [48]:
print(np.mean(pct_improve))
print(np.std(pct_improve))

0.44308155018398865
0.36977474030504487


In [24]:
both_scores = pd.concat([

In [42]:
print(np.mean(const_score_list))
print(np.std(const_score_list))

print(np.mean(opt_score_list))
print(np.std(opt_score_list))




1442.396406039848
309.2967187625872
1975.296639566152
88.2177005222615


In [43]:
1+ (np.mean(opt_score_list) - np.mean(const_score_list))/np.mean(const_score_list) 

1.3694547707515445

In [38]:
exes = np.concatenate((np.ones_like(const_score), np.zeros_like(opt_score)))
whys = np.concatenate((const_score/100, opt_score/100))

df = pd.DataFrame({'Constant Speed':(const_score/100), 'Optimized Speed':(opt_score/100)})
plt.figure()
plt.ylabel('USD/Hour')
plt.title('Value generated by sorting: \n25 procedurally generated infeeds')
sns.violinplot(data = df, cut=0, orient='v')
# sns.violinplot(x = ['Constant Speed', 'Optimized Speed'], y = whys)

<Axes: title={'center': 'Value generated by sorting: \n25 procedurally generated infeeds'}, ylabel='USD/Hour'>

In [32]:
np.linalg.pinv(at)

array([[2., 2.],
       [1., 1.]])

In [33]:
C = np.array([[2, -1, 0], 
              [-1, 2, -1], 
              [0, -1, 2]])

In [34]:
np.linalg.eig(C)

(array([3.41421356, 2.        , 0.58578644]),
 array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
        [ 7.07106781e-01,  4.05405432e-16,  7.07106781e-01],
        [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))

In [52]:
plt.scatter(np.zeros_like(opt_score), opt_score)
plt.scatter(np.ones_like(const_score), const_score)


In [51]:
%matplotlib qt